package proveMaxGrupo64.Vistas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proveMaxGrupo64.AccesoADatos.CompraData;
import proveMaxGrupo64.AccesoADatos.ProveedorData;
import proveMaxGrupo64.Entidades.Compra;
import proveMaxGrupo64.Entidades.Proveedor;

public class ComprasaUnProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ComprasaUnProveedor
     */
    public ComprasaUnProveedor() {
        initComponents();
        this.setSize(500, 450);
        this.setTitle("Compras por Proveedor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtIDProveedor = new javax.swing.JTextField();
        jbBuscarProveedor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtComprasPorProveedor = new javax.swing.JTable();
        jtProveedorBuscado = new javax.swing.JTextField();
        jbBuscarPorNombre = new javax.swing.JButton();
        jbNuevaConsulta = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 153));
        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(500, 450));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 450));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Compras por Proveedor");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione Proveedor por ID:");

        jbBuscarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jbBuscarProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbBuscarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jbBuscarProveedor.setText("Buscar");
        jbBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarProveedorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Seleccione Proveedor por Razón Social:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtIDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbBuscarProveedor)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtIDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarProveedor))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jtComprasPorProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtComprasPorProveedor);

        jtProveedorBuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtProveedorBuscadoActionPerformed(evt);
            }
        });
        jtProveedorBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtProveedorBuscadoKeyReleased(evt);
            }
        });

        jbBuscarPorNombre.setBackground(new java.awt.Color(255, 255, 255));
        jbBuscarPorNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbBuscarPorNombre.setForeground(new java.awt.Color(0, 0, 0));
        jbBuscarPorNombre.setText("Buscar");
        jbBuscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarPorNombreActionPerformed(evt);
            }
        });

        jbNuevaConsulta.setBackground(new java.awt.Color(255, 255, 255));
        jbNuevaConsulta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbNuevaConsulta.setForeground(new java.awt.Color(0, 0, 0));
        jbNuevaConsulta.setText("Nueva Consulta");
        jbNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbNuevaConsulta)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jtProveedorBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBuscarPorNombre)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(jtProveedorBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 133, Short.MAX_VALUE)
                        .addComponent(jbBuscarPorNombre)
                        .addGap(17, 17, 17)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNuevaConsulta)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtProveedorBuscadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtProveedorBuscadoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jtProveedorBuscadoKeyReleased

    private void jbBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarProveedorActionPerformed
        String idProvee = jtIDProveedor.getText();
        int idProveedor = Integer.parseInt(idProvee);

        // Creo un objeto Proveedor con el ID ingresado
        Proveedor proveedor = new Proveedor();
        proveedor.setIdProveedor(idProveedor);

        CompraData compraData = new CompraData();
        List<Compra> comprasProveedor = compraData.contarComprasProveedor(proveedor);
 
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Compra");
        modelo.addColumn("Fecha Compra");
        for (Compra compra : comprasProveedor) {
            modelo.addRow(new Object[]{
                compra.getIdCompra(),
                compra.getFecha(),});
        }

        jtComprasPorProveedor.setModel(modelo);
    }//GEN-LAST:event_jbBuscarProveedorActionPerformed

    private void jbBuscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarPorNombreActionPerformed
        // TODO add your handling code here:
        String proveedorBuscado = jtProveedorBuscado.getText();
        CompraData provee = new CompraData();

    // Llama al método que cuenta las compras por razonSocial
provee.contarVecesComprasPorRazonSocial(proveedorBuscado);

//
//    // Llama al método que cuenta las compras por razonSocial
//    int numCompras = contarComprasPorRazonSocial(proveedorBuscado);
//
//    // Muestra el número de compras en un JOptionPane
//    JOptionPane.showMessageDialog(this, "Número de compras realizadas al proveedor " + proveedorBuscado + ": " + numCompras, "Número de Compras", JOptionPane.INFORMATION_MESSAGE);
//
//    // Llena la tabla con los datos de las compras del proveedor
    llenarTablaComprasPorProveedor(proveedorBuscado);
//        String Proveedorbuscado = jtProveedorBuscado.getText();
//        CompraData provee = new CompraData();
        List<Compra> comprasProveedor = provee.contarComprasPorRazonSocial(proveedorBuscado);
//
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Compra");
        modelo.addColumn("Fecha Compra");
        for (Compra compra : comprasProveedor) {
            modelo.addRow(new Object[]{
                compra.getIdCompra(),
                compra.getFecha(),});
        }

        jtComprasPorProveedor.setModel(modelo);
    }//GEN-LAST:event_jbBuscarPorNombreActionPerformed

    private void jbNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaConsultaActionPerformed
        // TODO add your handling code here:
        jtIDProveedor.setText("");
        jtProveedorBuscado.setText("");

        // Limpiar tabla
        DefaultTableModel modelo = (DefaultTableModel) jtComprasPorProveedor.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_jbNuevaConsultaActionPerformed

    private void jtProveedorBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtProveedorBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtProveedorBuscadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscarPorNombre;
    private javax.swing.JButton jbBuscarProveedor;
    private javax.swing.JButton jbNuevaConsulta;
    private javax.swing.JTable jtComprasPorProveedor;
    private javax.swing.JTextField jtIDProveedor;
    private javax.swing.JTextField jtProveedorBuscado;
    // End of variables declaration//GEN-END:variables


private void llenarTablaComprasPorProveedor(String razonSocial) {
    CompraData provee = new CompraData();
    List<Compra> comprasProveedor = provee.contarComprasPorRazonSocial(razonSocial);

    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID Compra");
    modelo.addColumn("Fecha Compra");

    // Agrega las filas a la tabla
    for (Compra compra : comprasProveedor) {
        modelo.addRow(new Object[]{
            compra.getIdCompra(),
            compra.getFecha()
        });
    }
    jtComprasPorProveedor.setModel(modelo);
}
}
