package proveMaxGrupo64.Vistas;

public class ConsultasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultas
     */
    public ConsultasView() {
        initComponents();
        this.setSize(665, 400);
        this.setTitle("Consultas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio2 = new javax.swing.JDesktopPane();
        jpFondo = new javax.swing.JPanel();
        jlConsultas = new javax.swing.JLabel();
        jbProductosPorCompra = new javax.swing.JButton();
        jbProveedoresPorProducto = new javax.swing.JButton();
        jbComprasProveedor = new javax.swing.JButton();
        jbProductosMasComprados = new javax.swing.JButton();
        jbProductosMenorStock = new javax.swing.JButton();
        jbProductosCompra = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jpFondo.setBackground(new java.awt.Color(0, 0, 102));

        jlConsultas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jlConsultas.setText("CONSULTAR");

        jbProductosPorCompra.setBackground(new java.awt.Color(255, 255, 255));
        jbProductosPorCompra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosPorCompra.setForeground(new java.awt.Color(0, 0, 0));
        jbProductosPorCompra.setText("Productos de una Compra");
        jbProductosPorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosPorCompraActionPerformed(evt);
            }
        });

        jbProveedoresPorProducto.setBackground(new java.awt.Color(255, 255, 255));
        jbProveedoresPorProducto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProveedoresPorProducto.setForeground(new java.awt.Color(0, 0, 0));
        jbProveedoresPorProducto.setText("Proveedores por Producto");
        jbProveedoresPorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProveedoresPorProductoActionPerformed(evt);
            }
        });

        jbComprasProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jbComprasProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbComprasProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jbComprasProveedor.setText("Compras a un Proveedor");
        jbComprasProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprasProveedorActionPerformed(evt);
            }
        });

        jbProductosMasComprados.setBackground(new java.awt.Color(255, 255, 255));
        jbProductosMasComprados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosMasComprados.setForeground(new java.awt.Color(0, 0, 0));
        jbProductosMasComprados.setText("Productos Más Comprados");
        jbProductosMasComprados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosMasCompradosActionPerformed(evt);
            }
        });

        jbProductosMenorStock.setBackground(new java.awt.Color(255, 255, 255));
        jbProductosMenorStock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosMenorStock.setForeground(new java.awt.Color(0, 0, 0));
        jbProductosMenorStock.setText("Productos de Menor Stock");
        jbProductosMenorStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosMenorStockActionPerformed(evt);
            }
        });

        jbProductosCompra.setBackground(new java.awt.Color(255, 255, 255));
        jbProductosCompra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosCompra.setForeground(new java.awt.Color(0, 0, 0));
        jbProductosCompra.setText("Productos de una Compra");
        jbProductosCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbProveedoresPorProducto)
                        .addGap(41, 41, 41)
                        .addComponent(jbComprasProveedor))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jbProductosCompra)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jlConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jbProductosMasComprados)
                                .addGap(39, 39, 39)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbProductosMenorStock)
                                    .addComponent(jbProductosPorCompra))))))
                .addGap(17, 24, Short.MAX_VALUE))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlConsultas)
                .addGap(61, 61, 61)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbProductosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbComprasProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProductosPorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbProveedoresPorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProductosMasComprados, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProductosMenorStock, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Escritorio2.setLayer(jpFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Escritorio2Layout = new javax.swing.GroupLayout(Escritorio2);
        Escritorio2.setLayout(Escritorio2Layout);
        Escritorio2Layout.setHorizontalGroup(
            Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
            .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Escritorio2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Escritorio2Layout.setVerticalGroup(
            Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Escritorio2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbProductosCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosCompraActionPerformed
        // TODO add your handling code here:

        ProducCompraPorFecha ppc = new ProducCompraPorFecha();
        ppc.setVisible(true);
        Escritorio2.add(ppc);
        Escritorio2.moveToFront(ppc);

    }//GEN-LAST:event_jbProductosCompraActionPerformed

    private void jbComprasProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprasProveedorActionPerformed
        // TODO add your handling code here:
        ComprasaUnProveedor cxp = new ComprasaUnProveedor();
        cxp.setVisible(true);
        Escritorio2.add(cxp);
        Escritorio2.moveToFront(cxp);

    }//GEN-LAST:event_jbComprasProveedorActionPerformed

    private void jbProductosPorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosPorCompraActionPerformed
        // TODO add your handling code here:
        ProductosdeUnaCompra ppc = new ProductosdeUnaCompra();
        ppc.setVisible(true);
        Escritorio2.add(ppc);
        Escritorio2.moveToFront(ppc);

    }//GEN-LAST:event_jbProductosPorCompraActionPerformed

    private void jbProveedoresPorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProveedoresPorProductoActionPerformed
        ProveePorProducto ppp = new ProveePorProducto();
        ppp.setVisible(true);
        Escritorio2.add(ppp);
        Escritorio2.moveToFront(ppp);

    }//GEN-LAST:event_jbProveedoresPorProductoActionPerformed

    private void jbProductosMasCompradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosMasCompradosActionPerformed
        // TODO add your handling code here:
        ProductosMasComprados pmc = new ProductosMasComprados();
        pmc.setVisible(true);
        Escritorio2.add(pmc);
        Escritorio2.moveToFront(pmc);

    }//GEN-LAST:event_jbProductosMasCompradosActionPerformed

    private void jbProductosMenorStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosMenorStockActionPerformed
        // TODO add your handling code here:
        ProductosdeMenorStock pms = new ProductosdeMenorStock();
        pms.setVisible(true);
        Escritorio2.add(pms);
        Escritorio2.moveToFront(pms);

    }//GEN-LAST:event_jbProductosMenorStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio2;
    private javax.swing.JButton jbComprasProveedor;
    private javax.swing.JButton jbProductosCompra;
    private javax.swing.JButton jbProductosMasComprados;
    private javax.swing.JButton jbProductosMenorStock;
    private javax.swing.JButton jbProductosPorCompra;
    private javax.swing.JButton jbProveedoresPorProducto;
    private javax.swing.JLabel jlConsultas;
    private javax.swing.JPanel jpFondo;
    // End of variables declaration//GEN-END:variables
}
