package proveMaxGrupo64.Vistas;

public class ConsultasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultas
     */
    public ConsultasView() {
        initComponents();
        this.setSize(665, 400);
        this.setTitle("Consultas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio2 = new javax.swing.JDesktopPane();
        jpFondo = new javax.swing.JPanel();
        jlConsultas = new javax.swing.JLabel();
        jbProductosPorCompra = new javax.swing.JButton();
        jbProveedoresPorProducto = new javax.swing.JButton();
        jbComprasProveedor = new javax.swing.JButton();
        jbProductosMasComprados = new javax.swing.JButton();
        jbProductosMenorStock = new javax.swing.JButton();
        jbProductosCompra = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1100, 510));

        jpFondo.setBackground(new java.awt.Color(0, 0, 102));
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlConsultas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jlConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sobre.png"))); // NOI18N
        jlConsultas.setText("*CONSULTAS*");
        jpFondo.add(jlConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 27, 168, -1));

        jbProductosPorCompra.setBackground(new java.awt.Color(0, 0, 102));
        jbProductosPorCompra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosPorCompra.setForeground(new java.awt.Color(255, 255, 255));
        jbProductosPorCompra.setText("Productos de una Compra");
        jbProductosPorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosPorCompraActionPerformed(evt);
            }
        });
        jpFondo.add(jbProductosPorCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 92, -1, 66));

        jbProveedoresPorProducto.setBackground(new java.awt.Color(0, 0, 102));
        jbProveedoresPorProducto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProveedoresPorProducto.setForeground(new java.awt.Color(255, 255, 255));
        jbProveedoresPorProducto.setText("Proveedores por Producto");
        jbProveedoresPorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProveedoresPorProductoActionPerformed(evt);
            }
        });
        jpFondo.add(jbProveedoresPorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 365, -1, 66));

        jbComprasProveedor.setBackground(new java.awt.Color(0, 0, 102));
        jbComprasProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbComprasProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jbComprasProveedor.setText("Compras a un Proveedor");
        jbComprasProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprasProveedorActionPerformed(evt);
            }
        });
        jpFondo.add(jbComprasProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 92, 192, 66));

        jbProductosMasComprados.setBackground(new java.awt.Color(0, 0, 102));
        jbProductosMasComprados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosMasComprados.setForeground(new java.awt.Color(255, 255, 255));
        jbProductosMasComprados.setText("Productos Más Comprados");
        jbProductosMasComprados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosMasCompradosActionPerformed(evt);
            }
        });
        jpFondo.add(jbProductosMasComprados, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 365, -1, 66));

        jbProductosMenorStock.setBackground(new java.awt.Color(0, 0, 102));
        jbProductosMenorStock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosMenorStock.setForeground(new java.awt.Color(255, 255, 255));
        jbProductosMenorStock.setText("Productos de Menor Stock");
        jbProductosMenorStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosMenorStockActionPerformed(evt);
            }
        });
        jpFondo.add(jbProductosMenorStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 365, -1, 66));

        jbProductosCompra.setBackground(new java.awt.Color(0, 0, 102));
        jbProductosCompra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbProductosCompra.setForeground(new java.awt.Color(255, 255, 255));
        jbProductosCompra.setText("Productos de una Compra");
        jbProductosCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosCompraActionPerformed(evt);
            }
        });
        jpFondo.add(jbProductosCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 92, -1, 66));

        Escritorio2.setLayer(jpFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Escritorio2Layout = new javax.swing.GroupLayout(Escritorio2);
        Escritorio2.setLayout(Escritorio2Layout);
        Escritorio2Layout.setHorizontalGroup(
            Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
            .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Escritorio2Layout.setVerticalGroup(
            Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbProductosCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosCompraActionPerformed
        // TODO add your handling code here:

        ProducCompraPorFecha ppc = new ProducCompraPorFecha();
        ppc.setVisible(true);
        Escritorio2.add(ppc);
        Escritorio2.moveToFront(ppc);

    }//GEN-LAST:event_jbProductosCompraActionPerformed

    private void jbComprasProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprasProveedorActionPerformed
        // TODO add your handling code here:
        ComprasaUnProveedor cxp = new ComprasaUnProveedor();
        cxp.setVisible(true);
        Escritorio2.add(cxp);
        Escritorio2.moveToFront(cxp);

    }//GEN-LAST:event_jbComprasProveedorActionPerformed

    private void jbProductosPorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosPorCompraActionPerformed
        // TODO add your handling code here:
        ProductosdeUnaCompra ppc = new ProductosdeUnaCompra();
        ppc.setVisible(true);
        Escritorio2.add(ppc);
        Escritorio2.moveToFront(ppc);

    }//GEN-LAST:event_jbProductosPorCompraActionPerformed

    private void jbProveedoresPorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProveedoresPorProductoActionPerformed
        ProveePorProducto ppp = new ProveePorProducto();
        ppp.setVisible(true);
        Escritorio2.add(ppp);
        Escritorio2.moveToFront(ppp);

    }//GEN-LAST:event_jbProveedoresPorProductoActionPerformed

    private void jbProductosMasCompradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosMasCompradosActionPerformed
        // TODO add your handling code here:
        ProductosMasComprados pmc = new ProductosMasComprados();
        pmc.setVisible(true);
        Escritorio2.add(pmc);
        Escritorio2.moveToFront(pmc);

    }//GEN-LAST:event_jbProductosMasCompradosActionPerformed

    private void jbProductosMenorStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosMenorStockActionPerformed
        // TODO add your handling code here:
        ProductosdeMenorStock pms = new ProductosdeMenorStock();
        pms.setVisible(true);
        Escritorio2.add(pms);
        Escritorio2.moveToFront(pms);

    }//GEN-LAST:event_jbProductosMenorStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio2;
    private javax.swing.JButton jbComprasProveedor;
    private javax.swing.JButton jbProductosCompra;
    private javax.swing.JButton jbProductosMasComprados;
    private javax.swing.JButton jbProductosMenorStock;
    private javax.swing.JButton jbProductosPorCompra;
    private javax.swing.JButton jbProveedoresPorProducto;
    private javax.swing.JLabel jlConsultas;
    private javax.swing.JPanel jpFondo;
    // End of variables declaration//GEN-END:variables
}
